Repository 9oormthon-univ/2024_DANPOONG_TEAM_44_FE, pull requests merged in 2024-11, with the labels that each got.

#2 [초기세팅] 초기세팅
  .eslintrc.json
  .prettierrc
  App.jsx
  babel.config.js
  package-lock.json
  package.json
  src/assets/index.js
  src/components/index.js
  src/constants/index.js
  src/context/index.js
  src/hooks/index.js
  src/navigation/index.js
  src/screens/community/index.js
  src/screens/home/index.js
  src/screens/houseInfo/index.js
  src/screens/login/index.js
  src/screens/myPage/index.js
  src/screens/signup/index.js
  src/services/index.js
  src/styles/index.js
  src/utils/index.js
Labels: ⚙️ Setting

#4 [공통] header 및 bottom tabs 구현
  App.jsx
  src/assets/icons/communityIcon.js
  src/assets/icons/homeIcon.js
  src/assets/icons/houseInfoIcon.js
  src/assets/icons/iconSvg.js
  src/assets/icons/myPageIcon.js
  src/hooks/useHideBottomTabs.js
  src/navigation/BottomTabs.jsx
  src/navigation/stack/CommunityStack.jsx
  src/navigation/stack/HomeStack.jsx
  src/navigation/stack/HouseInfoStack.jsx
  src/navigation/stack/LoginSignupStack.jsx
  src/navigation/stack/MyPageStack.jsx
  src/navigation/stack/index.js
  src/screens/Start.jsx
  src/screens/community/Chat.jsx
  src/screens/community/Community.jsx
  src/screens/community/ViewPost.jsx
  src/screens/community/WritePost.jsx
  src/screens/community/index.js
  src/screens/home/FavoriteHomes.jsx
  src/screens/home/Home.jsx
  src/screens/home/index.js
  src/screens/houseInfo/FindAgent.jsx
  src/screens/houseInfo/HouseInfo.jsx
  src/screens/houseInfo/MarketPriceCheck.jsx
  src/screens/houseInfo/index.js
  src/screens/login/Login.jsx
  src/screens/myPage/AreaSetting.jsx
  src/screens/myPage/MyChat.jsx
  src/screens/myPage/MyPage.jsx
  src/screens/myPage/MyPost.jsx
  src/screens/myPage/index.js
  src/screens/signup/Signup.jsx
  src/screens/signup/SignupArea.jsx
  src/screens/signup/SignupNickname.jsx
  src/screens/signup/index.js
Labels: ✨ Feat

#7 :sparkles:[feat]:로그인 회원가입
  App.jsx
  app.json
  src/assets/images/home/service1.png
  src/assets/images/home/service2.png
  src/assets/images/home/service3.png
  src/assets/images/home/service4.png
  src/assets/images/home1.png
  src/assets/images/home2.png
  src/assets/images/homeinfo1.png
  src/assets/images/homeinfo2.png
  src/assets/images/houseinfo/apt_image.png
  src/assets/images/houseinfo/multi_image.png
  src/assets/images/houseinfo/off_image.png
  src/assets/images/kakao_map_button.png
  src/assets/images/kakaomap.png
  src/assets/kakao_login_medium_wide.png
  src/assets/splash.png
  src/assets/zip_logo.png
  src/navigation/stack/LoginSignupStack.jsx
  src/screens/Splash.jsx
  src/screens/Start.jsx
  src/screens/login/Login.jsx
  src/screens/signup/Signup.jsx
  src/screens/signup/SignupArea.jsx
  src/screens/signup/SignupNickname.jsx
Labels: ✨ Feat

#9 Feature/#8/메인 홈 UI
  src/assets/icons/iconSvg.js
  src/assets/images/home/realestateinfo/RealEstateInfo1.png
  src/assets/images/home/realestateinfo/RealEstateInfo2.png
  src/assets/images/home/realestateinfo/RealEstateInfo3.png
  src/assets/images/home/realestateinfo/RealEstateInfo4.png
  src/navigation/stack/HomeStack.jsx
  src/screens/home/BuildingInfo.jsx
  src/screens/home/BuildingRegister.jsx
  src/screens/home/FavoriteHomes.jsx
  src/screens/home/Home.jsx
  src/screens/home/RealEstateInfo.jsx
  src/screens/home/index.js
Labels: ✨ Feat

#10 [커뮤니티] 커뮤니티 UI
  coderabbit.yaml
  package-lock.json
  package.json
  src/assets/icons/iconSvg.js
  src/components/community/ChatInput.jsx
  src/components/community/ChatMessage.jsx
  src/components/community/CommunityItem.jsx
  src/components/community/ImageSlider.jsx
  src/constants/mockData.js
  src/navigation/stack/CommunityStack.jsx
  src/screens/community/Chat.jsx
  src/screens/community/Community.jsx
  src/screens/community/ViewPost.jsx
  src/screens/community/WritePost.jsx
  src/utils/DateUtils.js
Labels: ✨ Feat, 🎨 Style

#15 [커뮤니티] 커뮤니티 UI 추가
  src/assets/icons/iconSvg.js
  src/components/common/DropdownMenu.jsx
  src/components/common/Header.jsx
  src/components/common/SearchHeader.jsx
  src/components/community/AddressItem.jsx
  src/components/modal/DeletePost.jsx
  src/constants/mockData.js
  src/navigation/stack/CommunityStack.jsx
  src/navigation/stack/MyPageStack.jsx
  src/screens/community/Chat.jsx
  src/screens/community/Community.jsx
  src/screens/community/PlaceUpload.jsx
  src/screens/community/SearchPost.jsx
  src/screens/community/ViewPost.jsx
  src/screens/community/WritePost.jsx
  src/screens/community/index.js
  src/screens/myPage/AreaSetting.jsx
  src/screens/myPage/MyChat.jsx
  src/screens/myPage/MyPage.jsx
  src/screens/myPage/MyPost.jsx
  src/utils/imageUtils.js
Labels: ✨ Feat, 🔨 Refactor

#16 [홈 정보] 홈 정보 UI
  package-lock.json
  package.json
  src/navigation/stack/HomeStack.jsx
  src/navigation/stack/HouseInfoStack.jsx
  src/screens/home/BuildingInfo.jsx
  src/screens/home/BuildingRegister.jsx
  src/screens/home/FavoriteHomes.jsx
  src/screens/home/Home.jsx
  src/screens/houseInfo/CalculateResult.jsx
  src/screens/houseInfo/FindAgent.jsx
  src/screens/houseInfo/HouseInfo.jsx
  src/screens/houseInfo/MarketPriceCheck.jsx
  src/screens/houseInfo/RentCalculate.jsx
  src/screens/houseInfo/apt/Apartment.jsx
  src/screens/houseInfo/apt/ApartmentInfo.jsx
  src/screens/houseInfo/apt/ApartmentResult.jsx
  src/screens/houseInfo/index.js
  src/screens/houseInfo/multi/MultiFamily.jsx
  src/screens/houseInfo/multi/MultiFamilyInfo.jsx
  src/screens/houseInfo/multi/MultiFamilyResult.jsx
  src/screens/houseInfo/officetel/OfficeTel.jsx
  src/screens/houseInfo/officetel/OfficeTelInfo.jsx
  src/screens/houseInfo/officetel/OfficeTelResult.jsx
Labels: ✨ Feat

#22 [메인] 부동산 적합도 테스트 UI
  .gitignore
  app.config.js
  app.json
  package-lock.json
  package.json
  src/assets/images/home/realestateinfo/test_image.png
  src/assets/images/home/slide/slide1.png
  src/assets/images/home/slide/slide2.png
  src/navigation/stack/HomeStack.jsx
  src/navigation/stack/LoginSignupStack.jsx
  src/screens/Start.jsx
  src/screens/home/BuildingInfo.jsx
  src/screens/home/Home.jsx
  src/screens/home/RealEstateCaution.jsx
  src/screens/home/RealEstateResult.jsx
  src/screens/home/RealEstateTest.jsx
  src/screens/home/RealEstateTestInfo.jsx
  src/screens/home/index.js
  src/screens/houseInfo/FindAgent.jsx
  src/screens/login/KakaoLogin.jsx
  src/screens/login/Login.jsx
  src/screens/login/index.js
  src/screens/signup/Signup.jsx
  src/screens/signup/SignupArea.jsx
  src/screens/signup/SignupNickname.jsx
Labels: 📬 API, ✨ Feat

#24 [API] 부동산 API 연동
  src/screens/home/BuildingInfo.jsx
  src/screens/home/BuildingRegister.jsx
  src/screens/houseInfo/apt/Apartment.jsx
  src/screens/houseInfo/apt/ApartmentInfo.jsx
  src/screens/houseInfo/apt/ApartmentResult.jsx
  src/screens/houseInfo/multi/MultiFamily.jsx
  src/screens/houseInfo/multi/MultiFamilyInfo.jsx
  src/screens/houseInfo/multi/MultiFamilyResult.jsx
  src/screens/houseInfo/officetel/OfficeTel.jsx
  src/screens/houseInfo/officetel/OfficeTelInfo.jsx
  src/screens/houseInfo/officetel/OfficeTelResult.jsx
Labels: 📬 API

#26 [커뮤니티] 커뮤니티 API 연결
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  src/assets/icons/iconSvg.js
  src/components/community/AddressItem.jsx
  src/components/community/CommunityItem.jsx
  src/components/community/ImageSlider.jsx
  src/hooks/useKakaoPlaceSearch.js
  src/screens/community/Community.jsx
  src/screens/community/PlaceUpload.jsx
  src/screens/community/SearchPost.jsx
  src/screens/community/ViewPost.jsx
  src/screens/community/WritePost.jsx
  src/screens/myPage/AreaSetting.jsx
  src/screens/myPage/MyPage.jsx
  src/screens/myPage/MyPost.jsx
  src/services/apiService.js
Labels: 📬 API

#29 [API] 회원가입, 로그인 기능 성공
  src/screens/login/Login.jsx
  src/screens/signup/Signup.jsx
  src/screens/signup/SignupArea.jsx
  src/screens/signup/SignupNickname.jsx
Labels: 📬 API
